# Generated by Django 5.2 on 2026-09-01 02:48

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Min


def dedupe_chat_messages(apps, schema_editor):
    """删除 (session, message_id) 重复的历史消息，每组保留最早写入的一条。"""
    ChatMessage = apps.get_model('langgraph_integration', 'ChatMessage')
    dup_groups = (
        ChatMessage.objects.values('session_id', 'message_id')
        .annotate(cnt=Count('id'), keep_id=Min('id'))
        .filter(cnt__gt=1)
    )
    for group in dup_groups.iterator():
        ChatMessage.objects.filter(
            session_id=group['session_id'], message_id=group['message_id']
        ).exclude(id=group['keep_id']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0031_alter_llmconfigbundleslot_enable_hitl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_chat_messages, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('session', 'message_id'), name='unique_session_chat_message'),
        ),
    ]
