# Generated by Django 5.2 on 2026-09-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0017_remove_document_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='embedding_service',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('ollama', 'Ollama'), ('xinference', 'Xinference'), ('custom', '自定义API'), ('orcarouter', 'OrcaRouter')], default='custom', help_text='选择嵌入服务提供商', max_length=50, verbose_name='嵌入服务'),
        ),
    ]
