# Generated by Django 5.2 on 2026-08-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0021_add_ai_action_step_type'),
        ('ui_automation', '0021_remove_uienvironmentconfig_browser_and_more'),
    ]

    operations = [
    ]
